### ISSUE TITLE
Publish as a pypi package

### ISSUE THREAD

**Issue by vvasuki** [tylergneill/skrutable#12]
I'd like to install and use this by running `pip install skrutable`. (Analogous to https://github.com/shreevatsa/sanskrit/issues/98 )

**Comment by gasyoun** [comment]
@tylergneill possible?

**Comment by tylergneill** [comment]
Recently did do: https://pypi.org/project/skrutable/1.2.0/. Just try "pip
install skrutable". Might just need one or two dependent packages manually
installed.
