### ISSUE TITLE
Something went wrong :-(

### ISSUE THREAD

**Issue by gasyoun** [tylergneill/skrutable#17]
If I enter http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/2_epic/ramayana/ram_03_u.htm
as

```
3.001.001a praviśya tu mahāraṇyaṃ daṇḍakāraṇyam ātmavān
3.001.001c dadarśa rāmo durdharṣas tāpasāśramamaṇḍalam
3.001.002a kuśacīraparikṣiptaṃ brāhmyā lakṣmyā samāvṛtam
3.001.002c yathā pradīptaṃ durdharśaṃ gagane sūryamaṇḍalam
```

it will fail.

![sdadsasasa](https://user-images.githubusercontent.com/80761/218305929-18d080cb-5ed7-4c38-8cb2-458836541b39.jpg)

Can it non-see the Gretil numbers with a regex?

Or only http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/2_epic/mbh/ext/bhgce__u.htm

```
dharmakṣetre kurukṣetre samavetā yuyutsavaḥ Bhg_01.001a [=MBh_06,023.001a]
māmakāḥ pāṇḍavāś caiva kim akurvata saṃjaya Bhg_01.001c [=MBh_06,023.001c]
```

will work with moving the numbers to the end?

**Comment by tylergneill** [comment]
Sorry, I'm not really interested in helping people enter data of this sort. Who's to say just how many different types of things the regex should be able to see past? If more people ask for such things, we can revisit.

Can't reproduce the full error page, by the way. I know that that page pops up sometimes (error-checking is not great yet), but I don't see it in this case.
