### ISSUE TITLE
Do not count empty lines {m: 0}    [0: ]

### ISSUE THREAD

**Issue by gasyoun** [tylergneill/skrutable#18]
None is none. If no input, no output, please.

```
 glgllgglgglllglg    {m: 24}    [16: rsrBjg]
llgglgglglgllglgg    {m: 26}    [17: srrjjgg]
                     {m: 0}    [0: ]
 lggllgglgglllgll    {m: 23}    [16: ysrBjl]
gglglggllggglglgg    {m: 28}    [17: trBmjgg]
                     {m: 0}    [0: ]
```

![sdasdasdasda](https://user-images.githubusercontent.com/80761/218312065-890c617f-95f4-4f58-b925-44eed383ab8d.jpg)

**Comment by tylergneill** [comment]
This is moot because multiple-verse input is obviously not supported. For now, I prefer this sort of signal that something is wrong with the required single-verse input.
