### ISSUE TITLE
Āryā metre not identified

### ISSUE THREAD

**Issue by drdhaval2785** [tylergneill/skrutable#3]
स्वः स्वर्गः सुरसद्म त्रिदशावासस्त्रिविष्टपं त्रिदिवम् । द्यौर्गौरमर्त्यभुवनं नाकः स्यादूर्ध्वलोकश्च ॥ ३ ॥

http://sanskritmetres.appspot.com/identify shows that it is an exact match for Āryā metre.

Output by skrutable is 
```
स्वः स्वर्गः सुरसद्म त्रिदशावासस्त्रिविष्टपं त्रिदिवम् । द्यौर्गौरमर्त्यभुवनं नाकः स्यादूर्ध्वलोकश्च ॥ ३ ॥

   gggllggl   [13]   [msgl]
   lggglgll   [12]   [yrll]
   llggglgl   [12]   [stgl]
llggggglggl   [18]   [smrgl]

    sva   ḥsva    rga    ḥsu     ra     sa    dma    tri
      g      g      g      l      l      g      g      l
     da     śā     vā     sa   stri     vi    ṣṭa     pa
      l      g      g      g      l      g      l      l
   ṃtri     di     va  mdyau   rgau     ra     ma   rtya
      l      l      g      g      g      l      g      l
    bhu     va     na    ṃnā     ka   ḥsyā     dū  rdhva     lo     ka    śca
      l      l      g      g      g      g      g      l      g      g      l

anuṣṭubh (ab: pathyā, cd: asamīcīna)
```

**Comment by tylergneill** [comment]
Ok, please give a look again. I've implemented some new options. For jātis, when the midpoint is marked, the new option "resplit max keep mid" should work best. The other options produce more errors, but different ones, depending on the specifics of the verse. I've tested this on the Saptaśatī and "resplit max keep mid" now gets nearly all of the verses right, except when there's a textual problem (spreadsheet attached if you're curious).
[sattasai resplit comparison.xlsx](https://github.com/tylergneill/skrutable/files/5902404/sattasai.resplit.comparison.xlsx)
 Thanks very much for this input. I'll be happy to know what you think so far.
