### ISSUE TITLE
upajāti ...: ajñātam [0: ]

### ISSUE THREAD

**Issue by gasyoun** [tylergneill/skrutable#9]
वने रणे शत्रुजलाग्निमध्ये
	महार्णवे पर्वतमस्तके वा ।
सुप्तं प्रमत्तं विषमस्थितं वा
	रक्षन्ति पुण्यानि पुराकृतानि ॥ ९९ ॥

Same as https://github.com/shreevatsa/sanskrit/issues/121, no result.

**Comment by tylergneill** [comment]
Not true, you just didn't set the input scheme.

lglggllglgg    {m: 17}    [11: jtjgg]
lglggllglgg    {m: 17}    [11: jtjgg]
gglggllglgg    {m: 18}    [11: ttjgg]
gglggllglgl    {m: 17}    [11: ttjgl]

    va    ne    ra    ṇe    śa   tru    ja    lā   gni    ma  dhye
     l     g     l     g     g     l     l     g     l     g     g
    ma    hā   rṇa    ve    pa   rva    ta    ma   sta    ke    vā
     l     g     l     g     g     l     l     g     l     g     g
    su  ptaṃ   pra    ma  ttaṃ    vi    ṣa    ma  sthi   taṃ    vā
     g     g     l     g     g     l     l     g     l     g     g
    ra   kṣa   nti    pu   ṇyā    ni    pu    rā    kṛ    tā    ni
     g     g     l     g     g     l     l     g     l     g     l

upajāti : upendravajrā [11: jtjgg], indravajrā [11: ttjgg]
